language: python

python:
  - 3.6

cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest>=3.6.0
  - pip install pytest-dependency pytest-mock requests-mock pytest>=3.6.0 "coverage<5.0" pytest-cov==2.4.0 python-coveralls
  - cd .. && git clone https://github.com/thu-coai/cotk.git && cd cotk && git checkout version_up && cd .. && pip install ./cotk --progress-bar off && cd seqGAN-tensorflow

script:
  - pytest test_seqGAN_tensorflow.py --cov=. --cov-report term-missing

deploy:
  - provider: script
    skip-cleanup: true
    script: coveralls
    on:
      all_branches: true
      condition: true
